import { useCallback, useEffect, useRef, useState } from 'react'
import { Box, Card, CardContent, Stack, Typography } from '@mui/material'
import QRCode from 'qrcode'
import { generateBadgeCode, mintCheckinToken } from '../../data/checkin.js'
import { ErrorState, LoadingState } from '../../components/ScreenState.jsx'
import { useAuth } from '../auth/useAuth.js'
import PageHeader from '../../components/PageHeader.jsx'
import { POINTS } from '../workout/summary.js'

/** mm:ss, from a count of seconds. */
function clock(seconds) {
  const m = Math.floor(seconds / 60)
  const s = seconds % 60
  return `${m}:${String(s).padStart(2, '0')}`
}

export default function BadgeScreen() {
  const { user } = useAuth()
  const [badge, setBadge] = useState(null)
  const [error, setError] = useState(null)
  const [secondsLeft, setSecondsLeft] = useState(0)
  // In-flight guard: every caller (mount, expiry tick, visibility handler)
  // goes through this one `mint`, so one guard here covers all of them.
  const mintingRef = useRef(false)
  // Flipped false on unmount so a mint that settles after the member has
  // navigated away doesn't call setState on a gone screen.
  const aliveRef = useRef(true)

  // React 19 StrictMode mounts effects twice in development. The cleanup below
  // flips aliveRef to false on unmount; resetting it here ensures the second
  // mount doesn't inherit the first mount's teardown.
  useEffect(() => {
    aliveRef.current = true
    return () => {
      aliveRef.current = false
    }
  }, [])

  // `generateBadgeCode()` lives here rather than in the render body:
  // react-hooks/purity forbids reading crypto's randomness during render, and
  // a token regenerated by every re-render would be a new database row per
  // keystroke elsewhere.
  const mint = useCallback(async () => {
    if (mintingRef.current) return
    mintingRef.current = true
    try {
      const row = await mintCheckinToken({ memberId: user.id, token: generateBadgeCode() })
      const dataUrl = await QRCode.toDataURL(row.token, { width: 320, margin: 1 })
      if (aliveRef.current) {
        // The deadline is the server-side LIFETIME counted from the moment the
        // response landed, never `expires_at` minus this device's clock: that
        // subtraction mixes two clocks, and a phone a minute fast would find
        // every fresh token already expired and mint in a loop.
        setBadge({ expiresAt: Date.now() + row.lifetimeMs, dataUrl, token: row.token })
        setError(null)
      }
    } catch (cause) {
      if (aliveRef.current) {
        setBadge(null)
        setError(cause)
      }
    } finally {
      mintingRef.current = false
    }
  }, [user.id])

  useEffect(() => {
    const init = async () => {
      await mint()
    }
    init()
  }, [mint])

  // The mint effect runs once, and a failed mint leaves `badge` null, so the
  // countdown effect below returns before it starts an interval. Without this
  // listener the error state is a dead end until the member navigates away and
  // back; with it the badge appears on its own the moment the phone reconnects.
  useEffect(() => {
    if (!error) return undefined
    window.addEventListener('online', mint)
    return () => window.removeEventListener('online', mint)
  }, [error, mint])

  useEffect(() => {
    if (!badge) return undefined

    const tick = () => {
      const remaining = badge.expiresAt - Date.now()
      setSecondsLeft(Math.max(0, Math.ceil(remaining / 1000)))
      // Minting stops while the page is hidden. A phone locked with the badge
      // open would otherwise write one row a minute for as long as it sat in a
      // pocket. The visibility listener below picks it back up.
      if (remaining <= 0 && document.visibilityState === 'visible') mint()
    }

    tick()
    const timer = setInterval(tick, 1000)
    const onVisible = () => {
      if (document.visibilityState === 'visible') tick()
    }
    document.addEventListener('visibilitychange', onVisible)

    return () => {
      clearInterval(timer)
      document.removeEventListener('visibilitychange', onVisible)
    }
  }, [badge, mint])

  return (
    <Stack spacing={3} sx={{ p: 2, alignItems: 'center', textAlign: 'center' }}>
      <PageHeader title="Access Badge" backTo="/m/profile" backLabel="Back to profile" />

      {/* A badge cannot be minted without a network: the token is a row. This
          is the second write in the app, after the password change, where the
          offline queue is the wrong tool -- a token replayed on reconnect is
          worth nothing to anyone. */}
      {error ? <ErrorState error={error} onRetry={mint} /> : null}

      {!badge && !error ? <LoadingState /> : null}

      {badge ? (
        <>
          <Card sx={{ p: 2 }}>
            <CardContent sx={{ p: 0, '&:last-child': { pb: 0 } }}>
              <Box
                component="img"
                src={badge.dataUrl}
                alt="Your access badge"
                sx={{ display: 'block', width: '100%', maxWidth: 320, height: 'auto' }}
              />
            </CardContent>
          </Card>

          <Stack spacing={0.5}>
            <Typography variant="h3" color="primary">
              Scan the QR code to enter the gym
            </Typography>
            <Typography color="text.secondary" role="status">
              {secondsLeft > 0
                ? `Valid for ${clock(secondsLeft)} — it renews on its own`
                : 'Renewing…'}
            </Typography>
            {/* Said here rather than only inside Rewards: a member who does not
                already know the points exist has no reason to open that screen,
                and this is the moment the points are actually earned. */}
            <Typography variant="body2" color="text.secondary">
              Worth {POINTS.checkin} points, once a day
            </Typography>
          </Stack>

          {/* Same token the QR encodes, as text: the way in when the code on
              screen won't scan -- cracked glass, glare, a broken desk camera --
              read aloud or typed into the scanner's manual field. */}
          <Stack spacing={0.5}>
            <Typography variant="body2" color="text.secondary">
              QR won't scan? Read this code to the front desk:
            </Typography>
            <Typography
              variant="h4"
              sx={{ fontFamily: 'monospace', letterSpacing: '0.1em', userSelect: 'all' }}
            >
              {badge.token.slice(0, 4)} {badge.token.slice(4)}
            </Typography>
          </Stack>
        </>
      ) : null}
    </Stack>
  )
}
